# Generated by Django 5.1 on 2024-10-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'docteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='AppWeb.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], max_length=50)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'docteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='AppWeb.customuser')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='AppWeb.customuser')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.availability')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage_per_day', models.IntegerField()),
                ('duration_in_days', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='AppWeb.appointment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('doctor', 'start_time', 'end_time'), name='unique_availability'),
        ),
    ]
